# Generated by Django 4.2.4 on 2023-09-01 20:47

from django.db import migrations
from my_app.models import HangmanWordBank

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]