# Generated by Django 4.2.4 on 2023-09-01 20:47

from django.db import migrations
from my_app.models import HangmanWordBank

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]



hangman_wordbank = [
    [
    {
      "word": "Grease",
      "hint": "Melted fat that can coagulate into a gelatinous form."
    },
    {
      "word": "Butter",
      "hint": "Saturated fat made from cow’s milk."
    },
    {
      "word": "Censor",
      "hint": "To prevent freedom of speech and expression."
    },
    {
      "word": "Chevy",
      "hint": "I drove mine to the levi but the levi was dry."
    },
    {
      "word": "Roller Derby",
      "hint": "Aggressive women going in a circle"
    },
    {
      "word": "Safari",
      "hint": "An expedition to hunt or observe animals in Africa."
    },
    {
      "word": "Detour",
      "hint": "A long, roundabout route."
    },
    {
      "word": "Auction",
      "hint": "A public sale where items are sold to the highest bidder."
    },
    {
      "word": "Pizza",
      "hint": "A type of pie traditionally made with tomatoes and cheese."
    },
    {
      "word": "Restaurant",
      "hint": "A place where people pay to sit and eat meals that are cooked and served to them."
    },
    {
      "word": "Pothole",
      "hint": "A break and erosion in the pavement."
    },
    {
      "word": "Premier",
      "hint": "The first showing of a play, movie, or TV show."
    },
    {
      "word": "Weekend",
      "hint": "Two non-working days of the week."
    },
    {
      "word": "Crane",
      "hint": "A tall, large machine used to move heavy objects."
    },
    {
      "word": "CSS",
      "hint": "The abbreviation for Cascading Style Sheet."
    },
    {
      "word": "Download",
      "hint": "The act of transferring data from the Internet."
    },
    {
      "word": "PHP",
      "hint": "The predominant server-side programming language."
    },
    {
      "word": "Chicken",
      "hint": "\"Winner winner, ________ dinner!!!\""
    },
    {
      "word": "NASCAR",
      "hint": "The National Association for Stock Car Auto Racing."
    },
    {
      "word": "Blu-ray",
      "hint": "The higher quality DVD replacement."
    },
    {
      "word": "Siri",
      "hint": "A personal digital assistant from Apple."
    }
  ]
]