# Generated by Django 4.2.4 on 2023-09-02 18:37

from django.db import migrations, models
from django.core.management import call_command
from my_app.models import UserProfile


def load_seed_data(apps, schema_editor):
    call_command('loaddata', 'my_app/seed_data/usernames.json')


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('is_online', models.BooleanField(null=True)),
            ],
        ),
        migrations.RunPython(load_seed_data),
    ]
